module HOSTS
  def HOSTS::hosts
    { 'x10' => { 
        'port_types' => {'E25' => 48, 'E100' => 6, 'Ma' => 1},
        'ports' => {
          'Eth 1/1/1'  => {  'label' => '1', 'remote' => {'host' => 'cop-e1', 'port' => 'enp1s0f0'} },
          'Eth 1/1/2'  => {  'label' => '2', 'remote' => {'host' => 'cop-e2', 'port' => 'enp1s0f0'} },
          'Eth 1/1/3'  => {  'label' => '3', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/4'  => {  'label' => '4', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/5'  => {  'label' => '5', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/6'  => {  'label' => '6', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/7'  => {  'label' => '7', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/8'  => {  'label' => '8', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/9'  => {  'label' => '9', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/10' => {  'label' => '10', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/11' => {  'label' => '11', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/12' => {  'label' => '12', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/13' => {  'label' => '13', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/14' => {  'label' => '14', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/15' => {  'label' => '15', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/16' => {  'label' => '16', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/17' => {  'label' => '17', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/18' => {  'label' => '18', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/19' => {  'label' => '19', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/20' => {  'label' => '20', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/21' => {  'label' => '21', 'remote' => {'host' => '', 'port' => ''}  },
          'Eth 1/1/22' => {  'label' => '22', 'remote' => {'host' => '', 'port' => ''}  },
          'Eth 1/1/23' => {  'label' => '23', 'remote' => {'host' => '', 'port' => ''}  },
          'Eth 1/1/24' => {  'label' => '24', 'remote' => {'host' => '', 'port' => ''}  },
          'Eth 1/1/25' => {  'label' => '25', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/26' => {  'label' => '26', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/27' => {  'label' => '27', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/28' => {  'label' => '28', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/29' => {  'label' => '29', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/30' => {  'label' => '30', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/31' => {  'label' => '31', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/32' => {  'label' => '32', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/33' => {  'label' => '33', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/34' => {  'label' => '34', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/35' => {  'label' => '35', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/36' => {  'label' => '36', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/37' => {  'label' => '37', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/38' => {  'label' => '38', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/39' => {  'label' => '39', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/40' => {  'label' => '40', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/41' => {  'label' => '41', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/42' => {  'label' => '42', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/43' => {  'label' => '43', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/44' => {  'label' => '44', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/45' => {  'label' => '45', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/46' => {  'label' => '46', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/47' => {  'label' => '47', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/48' => {  'label' => '48', 'remote' => {'host' => '', 'port' => ''} },
          'Eth 1/1/49' => {  'label' => 'F1', 'remote' => {'host' => '', 'port' => ''}},
          'Eth 1/1/50' => {  'label' => 'F2', 'remote' => {'host' => '', 'port' => ''}},
          'Eth 1/1/51' => {  'label' => 'F3', 'remote' => {'host' => 'x11', 'port' => 'Eth 1/1/51'}},
          'Eth 1/1/52' => {  'label' => 'F4', 'remote' => {'host' => 'x11', 'port' => 'Eth 1/1/52'}},
          'Eth 1/1/53:1' => {  'label' => 'F5', 'remote' => {'host' => 'x6', 'port' => 'Fo 1/53'} },
          'Eth 1/1/54:1' => {  'label' => 'F6', 'remote' => {'host' => 'x6', 'port' => 'Fo 1/54'} },
          'Ma 1/1/1'  => {  'label' => 'M', 'remote' => {'host' => 'x1', 'port' => 'Gi 1/39'}, 'ip'=>'172.31.80.10' },
        }
      }
    }
  end
end
